name: Ubuntu

on:
  pull_request:
    types: [synchronize, opened]
  push:
    branches:
      - main

env:
  OPENCV_VERSION: 4.7.0
  OPENCV_CACHE_VERSION: 1

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout OpenCvSharp
      uses: actions/checkout@v3
      with:
        path: opencvsharp
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt-get install -y --no-install-recommends \
          g++ \
          make \
          cmake \
          libtbb-dev \
          libatlas-base-dev 

    - name: Checkout OpenCV
      uses: actions/checkout@v3
      with:
          repository: opencv/opencv
          path: opencv
          ref: ${{ env.OPENCV_VERSION }}
          
    - name: Build OpenCV
      if: steps.opencv-cache.outputs.cache-hit != 'true'
      run: |
        cd ${{github.workspace}}/opencv
        cmake \
          -S . \
          -B build \
          -D CMAKE_BUILD_TYPE=Release \
          -D BUILD_SHARED_LIBS=OFF \
          -D ENABLE_CXX11=ON \
          -D BUILD_EXAMPLES=OFF \
          -D BUILD_DOCS=OFF \
          -D BUILD_PERF_TESTS=OFF \
          -D BUILD_TESTS=OFF \
          -D BUILD_JAVA=OFF \
          -D BUILD_opencv_apps=OFF \
          -D BUILD_LIST=core,imgproc,imgcodecs \
          -D WITH_GSTREAMER=OFF \
          -D WITH_ADE=OFF \
          -D BUILD_WEBP=ON \
          -D WITH_WEBP=ON \
          -D WITH_PROTOBUF=OFF \
          -D WITH_QUIRC=OFF \
          -D OPENCV_ENABLE_NONFREE=ON \
          -D CMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/opencv_artifacts 
        cd build
        make -j2
        make install
        sudo ldconfig
          
    - name: Build OpenCvSharpExtern
      run: |
        cd ${{github.workspace}}/opencvsharp/cpp
        cmake -S . -B build \
          -D CMAKE_BUILD_TYPE=Release \
          -D CMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/opencv_artifacts
        cmake --build build -- -j2

    - name: Test OpenCvSharpExtern
      working-directory: ${{github.workspace}}/opencvsharp/cpp/build
      run: ctest
